substitutions:
  _SERVICE_NAME: bms-4-admin-web
  _NEXT_PUBLIC_SUPABASE_URL: ""
  _NEXT_PUBLIC_SUPABASE_ANON_KEY: ""
  _NEXT_PUBLIC_SUPABASE_TEMPLATE_BUCKET: resume-templates

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}
      - --build-arg
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - --build-arg
      - NEXT_PUBLIC_SUPABASE_TEMPLATE_BUCKET=${_NEXT_PUBLIC_SUPABASE_TEMPLATE_BUCKET}
      - -t
      - gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest
      - .

images:
  - gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest
